# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
    - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build seto
      run: go build -o build/seto ./cmd/seto/main.go

    - name: Build setoc
      run: go build -o build/setoc ./cmd/setoc/main.go

    - uses: actions/upload-artifact@v4
      with:
        name: go-build
        path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: go-build
        path: build/

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --generate-notes

    - name: Upload artifacts to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' build/*
        --repo '${{ github.repository }}'
